### PR TITLE
test: first pass at integration tests using rhoaster

### PR DESCRIPTION
**Pull request by lance**
This PR contains an outline integration tests in the form of some simple tests that can be run with `npm run test:integration`. To run the tests, you will need to be logged into an OpenShift cluster (this could be `minishift` on your `localhost`.

The integration tests will deploy the application under test, wait for the application deployment to become available, then relinquish control to the testing framework. Tests are executed against the application API using `supertest` and `tape` together. Once the integration tests have completed, the application will be undeployed.

### CODE REVIEW

**Comment by lance** [comment]
The `rhoaster` integration test framework is very new and can be found [here](https://github.com/bucharest-gold/rhoaster).

**Comment by gastaldi** [comment]
For a minute I thought it was based on https://github.com/forge/roaster

**Comment by lance** [comment]
@gastaldi hopefully there won't be too much confusion about that!

**Comment by helio-frota** [comment]
LGTM
Running this on travis and having all green is a plus for sure.

**Comment by helio-frota** [comment]
linking with: https://github.com/bucharest-gold/entente/issues/151

**Review by helio-frota — APPROVED** [review]

**Comment by lholmquist** [comment]
Just ran the test for the greeting-service and it worked!

i noticed that the undeploy only cleans up "application" specific stuff, i wonder if we should also be deleting the builds/imagestream that it creates too?  that would be a nodeshift issue though

**Pull request closed without merging**
